### ISSUE TITLE
Hanging!

### ISSUE THREAD

**Issue by innat** [ahmedfgad/CIFAR10CNNFlask#1]
I's trying to understand your code for educational purposes. However at the time i run `CIFARTrainCNN.py` python file , my PC hung up. I've `core i5 6gen 3.3Gz ` wth  `8GB` ram. Will you please suggest me what's the minimum requirement of PC configuration or it happens for something else. Thanks.

**Comment by ahmedfgad** [comment]
You can decrease the percent of data used in training. This might makes the training faster.
The percent can be changed using line 270 in the **CIFARTrainCNN.py** file.
`percent = 80 #percent of samples to be included in each path.`
